services:
  - type: web
    name: roblox-version-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromSecret: discord_bot_token
